//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.payments = new HashSet<payment>();
        }
    
        public int cust_id { get; set; }
        public string fname { get; set; }
        public string lastname { get; set; }
        public string cnic { get; set; }
        public string cell_no { get; set; }
        public string Address { get; set; }
        public Nullable<int> booking_id { get; set; }
    
        public virtual booking booking { get; set; }
        public virtual ICollection<payment> payments { get; set; }
    }
}
