//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datalayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hrsEntitiess : DbContext
    {
        public hrsEntitiess()
            : base("name=hrsEntitiess")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admin> admins { get; set; }
        public DbSet<booking> bookings { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<record> records { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<room> rooms { get; set; }
        public DbSet<payment> payments { get; set; }
    }
}
