//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int pay_id { get; set; }
        public Nullable<int> cust_id { get; set; }
        public Nullable<int> Booking_id { get; set; }
        public int rent { get; set; }
        public Nullable<int> room_service { get; set; }
        public Nullable<int> total { get; set; }
    
        public virtual booking booking { get; set; }
        public virtual customer customer { get; set; }
    }
}
