//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class record
    {
        public int Id { get; set; }
        public string fname { get; set; }
        public string lastname { get; set; }
        public string CNIC_ { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> Booking_date { get; set; }
        public Nullable<System.DateTime> leaving_date { get; set; }
        public Nullable<int> room_ { get; set; }
        public Nullable<int> room_service { get; set; }
        public Nullable<int> amount { get; set; }
        public string cell_no { get; set; }
    }
}
