//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class room
    {
        public room()
        {
            this.bookings = new HashSet<booking>();
        }
    
        public int room_ { get; set; }
        public Nullable<int> rent { get; set; }
        public string room_type { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<booking> bookings { get; set; }
    }
}
