//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.admins = new HashSet<admin>();
        }
    
        public int Id { get; set; }
        public string user_name { get; set; }
        public string last_name { get; set; }
        public string password { get; set; }
        public string cell_no { get; set; }
        public string Address { get; set; }
        public string cnic_ { get; set; }
        public Nullable<int> booking_id { get; set; }
    
        public virtual ICollection<admin> admins { get; set; }
        public virtual booking booking { get; set; }
    }
}
